import type { Feature } from '../types.js';

export const core: Feature = {
  name: 'Core',
  description: 'React 19 + TypeScript + Vite 7 + Tailwind CSS v4',
  required: true,
  includes: [
    'React 19 with TypeScript (~5.9.0)',
    'Vite 7 build system',
    'Tailwind CSS v4 with Vite plugin',
    'Inter variable font (@fontsource-variable/inter)',
    'Environment validation with Zod (src/lib/env.ts)',
    'cn() class merge utility (clsx + tailwind-merge)',
    'Basic SEO component (React 19 native head hoisting)',
    'App configuration (src/lib/config.ts)',
    'Type definitions',
    'ErrorBoundary component with reset functionality',
  ],
  dependencyNames: ['@fontsource-variable/inter', 'clsx', 'react', 'react-dom', 'tailwind-merge', 'zod'],
  devDependencyNames: [
    '@tailwindcss/vite',
    '@types/node',
    '@types/react',
    '@types/react-dom',
    '@vitejs/plugin-react',
    '@react-spa-scaffold/tsconfig',
    'tailwindcss',
    'typescript',
    'vite',
  ],
  files: [
    'src/main.tsx',
    'src/App.tsx',
    'src/index.css',
    'src/vite-env.d.ts',
    'src/lib/config.ts',
    'src/lib/env.ts',
    'src/lib/utils.ts',
    'src/lib/index.ts',
    'src/types/index.ts',
    'src/hooks/index.ts',
    'src/components/shared/SEO/SEO.tsx',
    'src/components/shared/SEO/index.ts',
    'src/components/shared/ErrorBoundary/ErrorBoundary.tsx',
    'src/components/shared/ErrorBoundary/index.ts',
    'src/components/shared/index.ts',
    'index.html',
    'vite.config.ts',
    'tsconfig.json',
    'tsconfig.app.json',
    'tsconfig.node.json',
    '.env.example',
    '.gitignore',
    'public/favicon.svg',
  ],
  testFiles: [
    'src/lib/utils.test.ts',
    'src/components/shared/SEO/SEO.test.tsx',
    'src/components/shared/ErrorBoundary/ErrorBoundary.test.tsx',
    'e2e/tests/home.spec.ts',
  ],
  patterns: ['component-shared', 'hook-effect', 'error-boundary', 'seo-component'],
  scripts: {
    dev: 'vite',
    build: 'tsc -b && vite build',
    preview: 'vite preview',
    typecheck: 'tsc --noEmit',
  },
  configFiles: [
    'vite.config.ts',
    'tsconfig.json',
    'tsconfig.app.json',
    'tsconfig.node.json',
    '.gitignore',
    'src/index.css',
  ],
};
