import type { Feature } from '../types.js';

export const testing: Feature = {
  name: 'Testing',
  description: 'Vitest + Testing Library + Playwright + MSW',
  required: false,
  includes: [
    'Vitest for unit testing',
    'React Testing Library',
    '@testing-library/user-event for interactions',
    'Playwright for E2E testing (Chromium)',
    'MSW (Mock Service Worker) for API mocking',
    'Test utilities (render, providers, mocks)',
    '80% coverage threshold (lines, functions, statements, branches)',
    'jsdom environment',
    'Example tests for components, hooks, stores, utilities',
    'MSW handlers for API endpoints',
    'Test fixtures for mock data',
  ],
  devDependencyNames: [
    '@playwright/test',
    '@testing-library/jest-dom',
    '@testing-library/react',
    '@testing-library/user-event',
    '@vitest/coverage-v8',
    'jsdom',
    'msw',
    'vitest',
  ],
  files: [
    'src/test-setup.ts',
    'src/test/mocks.ts',
    'src/test/providers.tsx',
    'src/test/index.ts',
    'src/mocks/handlers/todos.ts',
    'src/mocks/handlers/index.ts',
    'src/mocks/fixtures/todos.ts',
    'src/mocks/fixtures/index.ts',
    'src/mocks/node.ts',
    'src/mocks/index.ts',
    'e2e/fixtures/',
    'e2e/tests/',
    'vitest.config.ts',
    'playwright.config.ts',
  ],
  scripts: {
    test: 'vitest run',
    'test:watch': 'vitest',
    'test:coverage': 'vitest run --coverage',
    e2e: 'playwright test --project=functional',
    'e2e:ui': 'playwright test --project=functional --ui',
  },
  configFiles: ['vitest.config.ts', 'playwright.config.ts', 'src/test-setup.ts'],
};
