import type { Feature } from '../types.js';

export const testing: Feature = {
  name: 'Testing',
  description: 'Vitest + Testing Library + Playwright + MSW',
  required: false,
  devDependencies: [
    '@playwright/test',
    '@testing-library/jest-dom',
    '@testing-library/react',
    '@testing-library/user-event',
    '@vitest/coverage-v8',
    'jsdom',
    'msw',
    'vitest',
  ],
  files: [
    'src/test-setup.ts',
    'src/test/mocks.ts',
    'src/test/providers.tsx',
    'src/test/index.ts',
    'src/mocks/handlers/todos.ts',
    'src/mocks/handlers/index.ts',
    'src/mocks/fixtures/todos.ts',
    'src/mocks/fixtures/index.ts',
    'src/mocks/node.ts',
    'src/mocks/index.ts',
    'e2e/fixtures/',
    'e2e/tests/',
    'vitest.config.ts',
    'playwright.config.ts',
  ],
  scripts: {
    test: 'vitest run',
    'test:watch': 'vitest',
    'test:coverage': 'vitest run --coverage',
    e2e: 'playwright test --project=desktop',
    'e2e:mobile': 'playwright test --project=mobile',
    'e2e:all': 'playwright test --project=desktop --project=mobile',
    'e2e:ui': 'playwright test --ui',
  },
  configFiles: ['vitest.config.ts', 'playwright.config.ts', 'src/test-setup.ts'],
};
